/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32h7xx_hal.h>
#include <stm32h7xx_hal_def.h>
#include <stm32h7xx.h>
#include <stm32h7xx_hal_conf.h>
#include <stm32h743xx.h>
#include <stm32h7xx_hal_gpio.h>
#include <system_stm32h7xx.h>

UART_HandleTypeDef huart3;

int main(void)
{
	__HAL_RCC_GPIOA_CLK_ENABLE();
	SystemCoreClock = 8000000;	// taktowanie 8Mhz
	HAL_Init();

	GPIO_InitTypeDef gpio;
	gpio.Mode = GPIO_MODE_AF_PP;
	gpio.Pin = GPIO_PIN_3;
	gpio.Pull = GPIO_PULLDOWN;
	gpio.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(GPIOA, &gpio);

	__HAL_RCC_USART3_CLK_ENABLE();


	huart3.Instance = USART3;
	huart3.Init.BaudRate = 115200;
	huart3.Init.WordLength = UART_WORDLENGTH_8B;
	huart3.Init.Parity = UART_PARITY_NONE;
	huart3.Init.StopBits = UART_STOPBITS_1;
	huart3.Init.HwFlowCtl = UART_HWCONTROL_NONE;
	huart3.Init.OverSampling = UART_OVERSAMPLING_16;
	huart3.Init.Mode = UART_MODE_TX_RX;
	HAL_UART_Init(&huart3);

	uint8_t signal = 0xAB;
    /* Loop forever */
	while(1)
	{
		HAL_UART_Transmit(&huart3, &signal, 1, 1000);
	}
}
